[package]
name = "erase-it"
version = "0.1.0"
description = "Local video masking and background removal"
edition = "2021"
license = "Apache-2.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
